### PR TITLE
Api transition

### LINKED ISSUE #1: API machinery improvements
Right now we are vendoring in API Machinery (good) but we aren't really using it all that well (bad)

Can we tidy up our API Machinery implementation and make it awesome?

### LINKED ISSUE #460: minCount and maxCound are removed from post-application cluster.yaml when creating cluster on AWS
The `cluster.yaml` file resulting after the `apply` does not contain anymore the `minCount` and `maxCount` fields.

Because of this we can't use `kubicorn getConfig`

### LINKED ISSUE #471: Use new community Cluster API
This is a big one and I will probably do it, unless somebody else wants to get themselves into some crazy Go work! 

But basically the Kubernetes community has been coming together and working towards a standardized **Cluster API** which can be found [here](https://github.com/kubernetes/kube-deploy/tree/master/cluster-api)

We need to support the new API in Kubicorn and move towards making this official moving forward.

### LINKED ISSUE #565: AWS provider won't scale once running
Hey all,

It seems that changing the `minCount` and `maxCount` primitives breaks a running AWS cluster.

Added like
```
...
  minCount: 1
  maxCount: 1
  name: test-aws.master
...
  minCount: 2
  maxCount: 3
  name: test-aws.node
  size: t2.medium
...
```
If added to running cluster, on `apply`:
```
$ kubicorn apply test-aws         
2018-03-08T11:56:28Z [ℹ]  Selected [fs] state store
2018-03-08T11:56:28Z [ℹ]  Loaded cluster: test-aws
2018-03-08T11:56:28Z [ℹ]  Init Cluster
2018-03-08T11:56:28Z [ℹ]  Query existing resources
2018-03-08T11:56:30Z [ℹ]  Resolving expected resources
2018-03-08T11:56:30Z [ℹ]  Reconciling
2018-03-08T11:56:31Z [ℹ]  InstanceProfile created: test-aws-KubicornMasterInstanceProfile
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x1062ec3]

goroutine 1 [running]:
github.com/kubicorn/kubicorn/cloud/amazon/public/resources.(*InstanceProfile).Apply(0xc4200b04c0, 0x1a43220, 0xc4206b7280, 0x1a43220, 0xc4207e79c0, 0xc420835500, 0x0, 0x1a43260, 0xc4200e90e0, 0x0, ...)
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/cloud/amazon/public/resources/instanceprofile.go:235 +0x773
github.com/kubicorn/kubicorn/cloud.(*AtomicReconciler).Reconcile(0xc420208040, 0xc42074c700, 0xc420835180, 0xc420835500, 0x0, 0x0)
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/cloud/atomic_reconciler.go:120 +0x3fd
github.com/kubicorn/kubicorn/cmd.RunApply(0x25cd680, 0x5832c0, 0xc4205c5cb0)
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:145 +0x7dc
github.com/kubicorn/kubicorn/cmd.ApplyCmd.func1(0xc4204c6240, 0xc42034a0b0, 0x1, 0x1)
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:54 +0x72
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc4204c6240, 0xc42034a070, 0x1, 0x1, 0xc4204c6240, 0xc42034a070)
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x25c3000, 0x18e6d20, 0x15, 0xc4205c5f68)
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:831 +0x2e4
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x25c3000, 0xc42004c0b8, 0x0)
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:784 +0x2b
github.com/kubicorn/kubicorn/cmd.Execute()
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/cmd/root.go:91 +0x2d
main.main()
	/home/joe/.local/go/src/github.com/kubicorn/kubicorn/main.go:22 +0x20
```

### LINKED ISSUE #573: AWS InstanceProfile fails if already exists
If the InstanceProfile already exists in AWS an application fails. Can be simulated by running a kubicorn apply with an instance profile that kubicorn attempts to create.

CC @nrb @detiber

### PR DESCRIPTION
**Pull request by kris-nova**
Gotta love a good transition.

Here is a working port to the cluster API.

1) Directives in the API aren't fleshed out (we use `providerConfig` for everything)
2) We aren't using CRD's yet (we just need to implement them as a state store)
3) We aren't running as a controller (but damn close)
4) We need to deprecate the autoscaling features (ASGs, etc)

Fixes #1 
Relates to #432 
Fixes #565 
Fixes #573
Fixes #471
Fixes #460

### CODE REVIEW

**Comment by nrb** [comment]
Will try to give this some time this week - +1 to removing ASGs and their ilk as a way to simplify things, though.

File: apis/cluster/cluster.go [hunk 1]
```diff
@@ -29,28 +32,197 @@ const (
...
+// This is useful for managing the legacy API in a clean way.
+// This will ignore errors from json.Unmarshal and will simply
+// return an empty config.
+func (c *Cluster) ProviderConfig() *ControlPlaneProviderConfig {
+	//providerConfig providerConfig
+	raw := c.ClusterAPI.Spec.ProviderConfig
+	providerConfig := &ControlPlaneProviderConfig{}
+	err := json.Unmarshal([]byte(raw), providerConfig)
+	if err != nil {
+		logger.Critical("Unable to unmarshal provider config: %v", err)
```
Comment (xmudrii) [inline apis/cluster/cluster.go]: Would it be a good idea to return error here as well, or that would just create a big overhead when using `ProviderConfig()`?
Also, is `logger.Critical` going to stop the code execution?

File: apis/cluster/cluster.go [hunk 2]
```diff
@@ -29,28 +32,197 @@ const (
...
+		// -------------------------------------------------
+
+		c.MachineSets = append(c.MachineSets, machineSet)
+	}
+}
+
+// ControlPlaneProviderConfig is the legacy Kubicorn API. We are temporarily storing
+// this as a ProviderConfig and these fields will slowly transition
+// into fields in the official cluster API
+type ControlPlaneProviderConfig struct {
```
Comment (xmudrii) [inline apis/cluster/cluster.go]: Some gofmt is needed here ;)

File: bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh [hunk 3]
```diff
@@ -43,8 +43,8 @@ systemctl daemon-reload
 systemctl restart kubelet
 
 # Parse kubicorn configuration file.
-TOKEN=$(cat /etc/kubicorn/cluster.json | jq -r '.values.itemMap.INJECTEDTOKEN')
```
Comment (xmudrii) [inline bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh]: Idea for another PR: above we have ${KUBERNETES_VERSION} stuff. Could we use Cluster API or API Machinery structures instead of those variables?

File: cloud/amazon/public/resources/launchconfiguration.go [hunk 4]
```diff
@@ -182,9 +181,12 @@ func (r *Lc) Apply(actual, expected cloud.Resource, immutable *cluster.Cluster)
 					if instance.PublicIpAddress != nil {
 						privip = *instance.PrivateIpAddress
 						pubip = *instance.PublicIpAddress
-						immutable.Values.ItemMap["INJECTEDMASTER"] = fmt.Sprintf("%s:%s", privip, immutable.KubernetesAPI.Port)
-						immutable.KubernetesAPI.Endpoint = pubip
+
+						providerConfig := immutable.ProviderConfig()
+						providerConfig.Values.ItemMap["INJECTEDMASTER"] = fmt.Sprintf("%s:%s", privip, immutable.ProviderConfig().KubernetesAPI.Port)
+						providerConfig.KubernetesAPI.Endpoint = pubip
```
Comment (xmudrii) [inline cloud/amazon/public/resources/launchconfiguration.go]: Just wondering, if we're injecting Private IP here, why is this using public IP? So we can access it outside the cluster?

File: apis/cluster/cluster.go (hunk 1 above)
Comment (kris-nova) [reply apis/cluster/cluster.go]: No, `logger.Critical` will not stop the code execution. https://github.com/kubicorn/kubicorn/blob/master/pkg/logger/logger.go#L70-L86

Returning the error would be smart, but would introduce a lot of problems with implementing the code in the rest of the program...

A few hundred references, each needing to check for an error that shouldn't ever happen.

Furthermore this is temporary, so I think it's okay

File: apis/cluster/cluster.go (hunk 2 above)
Comment (kris-nova) [reply apis/cluster/cluster.go]: I will run `gofmt` thanks

File: bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh (hunk 3 above)
Comment (kris-nova) [reply bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh]: yes we can make a lot of improvements here

File: cloud/amazon/public/resources/launchconfiguration.go (hunk 4 above)
Comment (kris-nova) [reply cloud/amazon/public/resources/launchconfiguration.go]: This is unchanged from before, just using provider config. I think this is how the nodes talk to the master so it doesnt need to be (and probably shouldnt be) private
