### PR TITLE
initapi,do: add cluster name validation

### LINKED ISSUE #458: Reconcile fails if cluster name contains "." with DigitalOcean profile
## Steps to reproduce

1. Create a new cluster
```
$> kubicorn create test.io --profile do
```

2. Run apply
```
$> kubicorn apply test.io                                                                                                                                             
2017-10-19T12:41:29-04:00 [✔]  Selected [fs] state store
2017-10-19T12:41:29-04:00 [✔]  Loaded cluster: test.io
2017-10-19T12:41:29-04:00 [✔]  Init Cluster
2017-10-19T12:41:29-04:00 [✔]  Query existing resources
2017-10-19T12:41:32-04:00 [✔]  Resolving expected resources
2017-10-19T12:41:32-04:00 [✔]  Reconciling
2017-10-19T12:41:33-04:00 [✔]  Using existing SSH Key [******]
2017-10-19T12:41:33-04:00 [✔]  Parsing bootstrap script from GitHub [https://raw.githubusercontent.com/kris-nova/kubicorn/master/bootstrap/vpn/openvpnMaster.sh]
2017-10-19T12:41:33-04:00 [✔]  Parsing bootstrap script from GitHub [https://raw.githubusercontent.com/kris-nova/kubicorn/master/bootstrap/digitalocean_k8s_ubuntu_16.04_master.sh]
2017-10-19T12:41:34-04:00 [✖]  Error during apply of atomic reconciler, attempting clawback: POST https://api.digitalocean.com/v2/droplets: 422 There was an error while trying to create your tags. Please try again.
2017-10-19T12:41:34-04:00 [!]
2017-10-19T12:41:34-04:00 [!]  Attempting to backtrack and cleanup created resources.
2017-10-19T12:41:34-04:00 [!]
2017-10-19T12:41:34-04:00 [✖]  Unable to commit state store: Nil cluster spec
```

### PR DESCRIPTION
**Pull request by xmudrii**
Closes #458

### CODE REVIEW

File: pkg/initapi/validate.go [hunk 1]
```diff
@@ -48,3 +49,10 @@ func validateSpotPriceOnlyForAwsCluster(initCluster *cluster.Cluster) error {
 	}
 	return nil
 }
+
+func validateClusterNameOnlyForDOCluster(initCluster *cluster.Cluster) error {
```
Comment (kris-nova) [inline pkg/initapi/validate.go]: So the function names here are documentation, as we print the name of the function if something fails so the function name should let the user know that is wrong and what they would need to fix in order to succeed.

So maybe `validateDigitalOceanClusterNameDoesNotContainPeriod` or something would be better? so the user would know what they need to fix

Comment (xmudrii) [reply pkg/initapi/validate.go]: @kris-nova I updated the function name to `validateDOClusterNameDoesNotContainPeriod`. Does it sound better?
